EXEC sp_rename 'dbo.ImportedData.[תאריך קליטה]', 'ImportDate', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[סכום תשלום]', 'PaymentAmount', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מטבע סכום תשלום]', 'PaymentCurrency', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[ריבית/עמלה]', 'Fee', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מטבע ריבית/עמלה]', 'FeeCurrency', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.חברה', 'Company', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[סוג כרטיס]', 'CardType', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מספר כרטיס]', 'CardNumber', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מספר ריכוז]', 'BatchNumber', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[סוג עסקה]', 'TransactionType', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מספר תשלומים]', 'Installments', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[תשלום מתוך תשלום]', 'CurrentPayment', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מספר בית עסק]', 'MerchantNumber', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[תאריך עסקה]', 'TransactionDate', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[סכום עסקה]', 'TransactionAmount', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מטבע סכום עסקה]', 'TransactionCurrency', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[סכום תקין]', 'ValidAmount', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מטבע תקין]', 'ValidCurrency', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[סכום התחשבנות]', 'SettlementAmount', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מטבע התחשבנות]', 'SettlementCurrency', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[תאריך זיכוי]', 'CreditDate', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[תאריך זיכוי בפועל]', 'ActualCreditDate', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.הנחה', 'Discount', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מספר שבא UID]', 'UID', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מספר שובר]', 'VoucherNumber', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מספר מסוף]', 'TerminalNumber', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[דמי ניהול]', 'ServiceFee', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[שער המרה]', 'ExchangeRate', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[סכום ריבית ניכיון]', 'DiscountAmount', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[מספר ברור]', 'ReversalNumber', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.[פרוט סיבת ברור]', 'ReversalReason', 'COLUMN';
EXEC sp_rename 'dbo.ImportedData.הערות', 'Notes', 'COLUMN';
